import { supabase } from '@/lib/supabase'

// CREATE - create a new tag
export async function createTag(userId: string, name: string, isAutoGenerated: boolean = false) {
  const { data, error } = await supabase
    .from('tags')
    .insert({
      user_id: userId,
      name,
      is_auto_generated: isAutoGenerated
    })
    .select()
    .single()
  return { data, error }
}

// READ - get all tags for a user
export async function getTags(userId: string) {
  const { data, error } = await supabase
    .from('tags')
    .select('*')
    .eq('user_id', userId)
    .order('name', { ascending: true })
  return { data, error }
}

// READ - get all tags for a specific card
export async function getCardTags(cardId: string) {
  const { data, error } = await supabase
    .from('card_tags')
    .select('*, tags(*)')
    .eq('card_id', cardId)
  return { data, error }
}

// CREATE - add a tag to a card
export async function addTagToCard(cardId: string, tagId: string) {
  const { data, error } = await supabase
    .from('card_tags')
    .insert({ card_id: cardId, tag_id: tagId })
    .select()
    .single()
  return { data, error }
}

// DELETE - remove a tag from a card
export async function removeTagFromCard(cardId: string, tagId: string) {
  const { data, error } = await supabase
    .from('card_tags')
    .delete()
    .eq('card_id', cardId)
    .eq('tag_id', tagId)
  return { data, error }
}

// DELETE - delete a tag completely
export async function deleteTag(tagId: string) {
  const { data, error } = await supabase
    .from('tags')
    .delete()
    .eq('id', tagId)
  return { data, error }
}

// ## What's Different Here
// ### This file handles TWO tables
// tags table      → the actual tags
// card_tags table → which tags are on which cards